---
abstract: 'simple, intuitive interface to the fork() system call'
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
build_requires:
  Test::More: 0
  vars: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Proc-Fork
requires:
  Carp: 0
  Exporter::Tidy: 0
  Object::Tiny::Lvalue: 0
  Scalar::Util: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/ap/Proc-Fork/issues
  homepage: http://github.com/ap/Proc-Fork
  repository: git://github.com/ap/Proc-Fork
version: 0.801
